### ISSUE TITLE
Using a property named "ID" throws serialization exception

### ISSUE THREAD

**Issue by KalyanChanumolu-MSFT** [Azure/azure-cosmos-table-dotnet#12]
Using a property named "ID" throws the below serialization exception

Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.String' because the type requires a JSON primitive value (e.g. string, number, boolean, null) to deserialize correctly.
To fix this error either change the JSON to a JSON primitive value (e.g. string, number, boolean, null) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'Id.$t', line 1, position 13.

"Id" seems to be a reserved system property. We should probably throw a more meaningful exception.

**Comment by KalyanChanumolu-MSFT** [comment]
Referencing [Git Issue# 35929](https://github.com/MicrosoftDocs/azure-docs/issues/35929)
Tagging @wmengmsft for info

**Comment by sakash279** [comment]
ID is a reserved field. Please reference the doc: https://docs.microsoft.com/en-us/azure/cosmos-db/faq#table
