### ISSUE TITLE
Namespace consolidation to Cosmos DB endpoint

### ISSUE THREAD

**Issue by MisinformedDNA** [Azure/azure-cosmos-table-dotnet#15]
The README.md (and other release notes) says

> The 2.0.0 Table SDK is in preview now... with... namespace consolidation to Cosmos DB endpoint

What does that mean exactly? Are Azure Tables being deprecated? Or absorbed into Cosmos? Will there still be a non-premium table storage option?

**Comment by ThomasWeiss** [comment]
@MisinformedDNA This remark only applies to the Table SDK, not the cloud services. We have consolidated our SDK efforts so you can now use a single SDK (the one from this repo) to interact with both Azure Table Storage and Cosmos DB's Table API.
There's currently no concrete plan to deprecate/retire the Azure Table Storage service.

**Comment by ritchxu** [comment]
@ThomasWeiss does this mean if we're using Azure Table Storage, we could switch from using [Microsoft.WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/9.3.3) to [Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table) without gap? Do we need to migrate data or just switch from one client library to the other?

**Comment by ThomasWeiss** [comment]
@ritchxu That is correct, you can just switch client libraries with no need to migrate your data. You may need to slightly adjust your `#using` statements as these 2 libraries don't work from the same namespaces, but the underlying API surface is identical.

**Comment by ritchxu** [comment]
@ThomasWeiss excellent, thanks for confirmation!
