### ISSUE TITLE
CloudTableClient.GetServiceStats is broken in the Microsoft.Azure.Cosmos.Table v2.0.0.0-preview

### ISSUE THREAD

**Issue by VladimirKhvostov** [Azure/azure-cosmos-table-dotnet#26]
CloudTableClient.GetServiceStats is broken in the Microsoft.Azure.Cosmos.Table. It was implemented in v 0.11.0-preview and was broken since then.

Repro:

            CloudStorageAccount storageAccount =
                CloudStorageAccount.Parse(connectionString);

            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

            TableRequestOptions tableRequestOptions = new TableRequestOptions()
            {
                LocationMode = LocationMode.SecondaryOnly
            };

            ServiceStats stats = tableClient.GetServiceStats(tableRequestOptions); 

Here is a response:
`<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>InvalidQueryParameterValue</m:code><m:message xml:lang="en-US">Value for one of the query parameters specified in the request URI is invalid.
RequestId:84509fe0-7002-006b-7b5c-d11c71000000
`

The problem is in the TableRequestOptions copy constructor.
It does not copy LocationMode property and as a result request is sent to the primary instead of secondary.

Here is a workaround:

             CloudStorageAccount storageAccount =
                CloudStorageAccount.Parse(connectionString);

            CloudTableClient tableClient = storageAccount.CreateCloudTableClient();

            TableRequestOptions tableRequestOptions = new TableRequestOptions()
            {
                LocationMode = LocationMode.SecondaryOnly
            };

            OperationContext operationContext = new OperationContext();
            operationContext.SendingRequest += (object sender, RequestEventArgs e) =>
            {
                string url = e.Request.RequestUri.AbsoluteUri;
                int dotIndex = url.IndexOf('.');
                string accountName = url.Substring(0, dotIndex);
                const string c_secondary = "-secondary";

                if (!accountName.EndsWith(c_secondary))
                {
                    e.Request.RequestUri = new System.Uri(accountName + c_secondary + url.Substring(dotIndex));
                }
            };

            ServiceStats stats = tableClient.GetServiceStats(tableRequestOptions, operationContext);

**Comment by sakash279** [comment]
fixed in table 1.0.7 
@VladimirKhvostov thanks for the fix
