### ISSUE TITLE
Deserialization of enums (or complex properties)

### ISSUE THREAD

**Issue by ordinaryorange** [Azure/azure-cosmos-table-dotnet#27]
**SDK version = 2.0.0**

I see that this lib has a dependency on Newtonsoft.Json.
And I'm probably making a big assumption here. But I was hoping that by adding the relevant Newtonsoft.Json attributes that the deserialization process would occur correctly.

Is this an implemented feature ?
Or am I maybe doing it wrong ?

**Issue reproduce steps**
```
var csa = CloudStorageAccount.Parse("mystring");
var tc = csa.CreateCloudTableClient();
var tbl = tc.GetTableReference("foo"); //Has string column 'AgeString' and int column 'AgeInt'
var qry = tbl.CreateQuery<Foo>();
qry.ToList(); //Foo members are not deserialized correctly

public class Foo : TableEntity
{
	[JsonConverter(typeof(StringEnumConverter))]
	public ages AgeString { get; set; } //defaults to 0 irrespective of data in Azure
	public ages AgeInt {get;set;} //same
}

public enum ages
{
	One,
	Two
	Three
}
```

**Comment by sakash279** [comment]
@ordinaryorange  v2.0.0 is a preview version, and we are currently making minor updates to v.1.x series. I would suggest switching to the latest in that for a more stable version.
The Newtonsoft.Json dependency is used by the Tables SDK internally to serialize/deserialize entity requests, indexing policy to cosmosDB endpoint etc. I don't think the example you have above is the correct intent of the dependency.  
If you want to serialize/deserialize to the enum type, it would have to be on the client side when you read the value from storage endpoint as a string. 
Please feel free to reopen if you don't think this is fully answered.
