### ISSUE TITLE
Major Performance Drop with 1.06 compared to old 9.3.3 Library

### ISSUE THREAD

**Issue by tfield-billgo** [Azure/azure-cosmos-table-dotnet#31]
SDK: 1.06
To reproduce:  Insert and read back large number of entities.  Noticeable performance decrease even with 1000.
Consistent: yes
Environment: Originally seen in deployment to azure services, reproduced locally with test app and test storage account.  Using Azure Storage, not cosmos.

We've been working to upgrade to the latest version of our libraries and have hit a major snag with azure tables.  The performance difference is pretty large and puts us into an unacceptable range for our clients.  I see version 2 should improve performance, but no details to what level.  Will performance be similar to 9.3.3?

Is there an ETA for the release of version 2?

What is the recommended path to upgrade to the latest storage libraries for Queues and Blobs without this major performance  decrease for Tables?

Below is the output of my test app.  Two identical sets of 1000 entities are inserted into two separate tables within the same account.  They are then read back with no filter.  The performance appears to be more noticeable with larger entities.  The tests show similar slowdowns to what we experienced in our test environment.

![image](https://user-images.githubusercontent.com/55755489/73559042-2f77db80-4409-11ea-9077-fbc232dc89f7.png)

**Comment by ssdevref** [comment]
I noticed that it was taking close to 60 seconds to load 700 via ExecuteQuerySegmentedAsync(filter, token)
when i dropped back to 1.0.5 it's now back to less than a second. The exact filter used is "(PartitionKey eq '1112222' and UserType eq 'Person')"

**Comment by tfield-billgo** [comment]
@ssdevref Thank you for the info!  I tested with v1.0.5 and saw no performance issues.

Also, here is a link to the test project: https://github.com/tfield-billgo/table-storage-library-test

**Comment by tfield-billgo** [comment]
I see there has been a new release for the library: https://docs.microsoft.com/en-us/azure/cosmos-db/table-sdk-dotnet-standard#107

Should these performance issues be fixed with this latest release?

**Comment by tfield-billgo** [comment]
This also seems to be related to https://github.com/Azure/azure-cosmos-table-dotnet/issues/43

**Comment by johnterickson** [comment]
I think this was fixed in 1.0.7. Is that right?

**Comment by tfield-billgo** [comment]
This seems to be fixed in 1.0.7
