### ISSUE TITLE
Returned partition and row keys from retrieve operation are null

### ISSUE THREAD

**Issue by baharedankoyuncu** [Azure/azure-cosmos-table-dotnet#41]
Hi,

I'm trying to fetch an entity from Azure Table Storage with the following code.
```
public async Task<T> GetAsync(string partitionKey, string rowKey)
{
    var operation = TableOperation.Retrieve<TableEntityAdapter<T>>(partitionKey, rowKey);
    var result = await _table.ExecuteAsync(operation);
    var complexEntity = result?.Result as TableEntityAdapter<T>;

    return complexEntity.OriginalEntity;
}
```
Inspecting the `TableResult` object namely `result` and looking into the `Result` property, I see the correct `PartitionKey` and `RowKey` properties. But the `OriginalEntity` property contain nulls for the partition and row key.

I can't seem to figure out why this happens but if I set the table operation to be `Retrieve<T>` instead of `Retrieve<TableEntityAdapter<T>>` then I get the correct keys except that now my I do not get the "complex entity".

I haven't been able to find anything about this behavior and currently blinded by this issue.

* SDK version
Microsoft.Azure.Cosmos.Table 1.0.6
* Whether the issue is consistent or sporadic
The issue is consistent.
* Environment Summary
Windows 10 Pro x64
Microsoft Visual Studio Professional 2019
Version 16.4.6
.NET Core 2.0 app but consumed by .NET Core 3.1 apps.

**Comment by christopheranderson** [comment]
Hi @baharedankoyuncu - thanks for reporting this issue.

We actually recommend not using TableEntityAdapter. Instead, we recommend directly extending TableEntity. TableEntityAdapter has some odd corner cases, as you've seen, that doesn't make it an ideal pattern.

I've created #58 to track deprecating this and then removing it in v2.

**Comment by AnakinBing** [comment]
Hi,
Use Reflection.

public T Get<T>(string partitionKey, string rowKey)
        {
            try
            {
                TableOperation operation = TableOperation.Retrieve<TableEntityAdapter<T>>(partitionKey, rowKey);
                TableResult result = table.Execute(operation);
                TableEntityAdapter<T> TableT = result.Result as TableEntityAdapter<T>;
                T t = TableT.OriginalEntity;
                PropertyInfo[] propertyInfos = typeof(T).GetProperties();
                foreach(PropertyInfo propertyInfo in propertyInfos)
                {
                    if (propertyInfo.Name == "PartitionKey")
                        propertyInfo.SetValue(t, TableT.PartitionKey);
                    if (propertyInfo.Name == "RowKey")
                        propertyInfo.SetValue(t, TableT.RowKey);
                    if (propertyInfo.Name == "Timestamp")
                        propertyInfo.SetValue(t, TableT.Timestamp);
                    if (propertyInfo.Name == "ETag")
                        propertyInfo.SetValue(t, TableT.ETag);
                }
                return t;
            }
            catch (Exception ex) 
            {
                throw ex;
            }
        }

**Comment by AnakinBing** [comment]
Hi
Use Reflection.

`public T Get<T>(string partitionKey, string rowKey)
        {
            try
            {
                TableOperation operation = TableOperation.Retrieve<TableEntityAdapter<T>>(partitionKey, rowKey);
                TableResult result = table.Execute(operation);
                TableEntityAdapter<T> TableT = result.Result as TableEntityAdapter<T>;
                T t = TableT.OriginalEntity;
                PropertyInfo[] propertyInfos = typeof(T).GetProperties();
                foreach(PropertyInfo propertyInfo in propertyInfos)
                {
                    if (propertyInfo.Name == "PartitionKey")
                        propertyInfo.SetValue(t, TableT.PartitionKey);
                    if (propertyInfo.Name == "RowKey")
                        propertyInfo.SetValue(t, TableT.RowKey);
                    if (propertyInfo.Name == "Timestamp")
                        propertyInfo.SetValue(t, TableT.Timestamp);
                    if (propertyInfo.Name == "ETag")
                        propertyInfo.SetValue(t, TableT.ETag);
                }
                return t;
            }
            catch (Exception ex) 
            {
                throw ex;
            }`

**Comment by AnakinBing** [comment]
Hi,
Use Reflection.

public T Get<T>(string partitionKey, string rowKey)
{
    TableOperation operation = TableOperation.Retrieve<TableEntityAdapter<T>>(partitionKey, rowKey);
    TableResult result = table.Execute(operation);
    TableEntityAdapter<T> TableT = result.Result as TableEntityAdapter<T>;
    T t = TableT.OriginalEntity;
    PropertyInfo[] propertyInfos = typeof(T).GetProperties();
    foreach(PropertyInfo propertyInfo in propertyInfos)
    {
        if (propertyInfo.Name == "PartitionKey")
            propertyInfo.SetValue(t, TableT.PartitionKey);
        if (propertyInfo.Name == "RowKey")
            propertyInfo.SetValue(t, TableT.RowKey);
        if (propertyInfo.Name == "Timestamp")
            propertyInfo.SetValue(t, TableT.Timestamp);
        if (propertyInfo.Name == "ETag")
            propertyInfo.SetValue(t, TableT.ETag);
    }
    return t;
}
