### ISSUE TITLE
`NameValidator` and `StorageErrorCodeStrings` missing after migrating to `Microsoft.Azure.Cosmos.Table`

### ISSUE THREAD

**Issue by seniorquico** [Azure/azure-cosmos-table-dotnet#5]
I'm working on migrating the Microsoft Orleans providers from `WindowsAzure.Storage` to `Microsoft.Azure.Cosmos.Table`. I've hit a snag with two classes that have changed visiblity. Namely, `NameValidator` and `StorageErrorCodeStrings`. These used to be `public`, but now they're `internal`. Here are examples of where they're being used (in my WIP fork/branch):

[`NameValidator.ValidateTableName`](https://github.com/seniorquico/orleans/blob/update-azure-storage-sdks/src/Azure/Shared/Storage/AzureTableUtils.cs#L209)
[`StorageErrorCodeStrings.ResourceNotFound`](https://github.com/seniorquico/orleans/blob/update-azure-storage-sdks/src/Azure/Shared/Storage/AzureTableUtils.cs#L75)
[`StorageErrorCodeStrings.OperationTimedOut`](https://github.com/seniorquico/orleans/blob/update-azure-storage-sdks/src/Azure/Shared/Storage/AzureTableUtils.cs#L158)

What are the recommended alternatives?

**Comment by donghexu** [comment]
Hi @seniorquico Thanks, I'll fix it in the next release.

**Comment by ggirard07** [comment]
@donghexu same thing with `TableErrorCodeStrings` now being internal in `Microsoft.Azure.Cosmos.Table` while it is public in `Microsoft.WindowsAzure.Storage.Table`.
Can you fix it too at the same time?

**Comment by seniorquico** [comment]
@donghexu Any idea when the next release will be ready?

**Comment by Vhab** [comment]
This is blocking us from migrating as well

**Comment by donghexu** [comment]
Hi All, we just release 1.0.4-preview with that fix. Please try it out. Thanks!
