### ISSUE TITLE
Can't upgrade Microsoft.Azure.Search to the latest version

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-cosmos-table-dotnet#53]
I'm stuck with version 7 because another package (Microsoft.Azure.Cosmos.Table) creates dependency issues. Can you please fix this issue?

![snippet](https://user-images.githubusercontent.com/62858360/78602095-7627ee80-781b-11ea-83bb-ea23bb431107.PNG)

**Comment by rnagpal** [comment]
@wmengmsft : Who could look into this and confirm if this issue is fixed?

**Comment by rnagpal** [comment]
Closing this as a dup of https://github.com/Azure/azure-cosmos-table-dotnet/issues/25.

@petro2050 : Can you please confirm the mitigation steps mentioned there and use that issue to follow up.
