### ISSUE TITLE
TableEntity.ConvertBack Throws NullReferenceException When Property Missing in TResult Type

### ISSUE THREAD

**Issue by kyleherzog** [Azure/azure-cosmos-table-dotnet#61]
Using 2.0.0-preview

Originally, came across this issue because a class definition changed by having a property removed.  However, data with the old definition still existed in the table storage.  

I've created the following test that exhibits the issue in a simplified manner.
```
[TestMethod]
public void QuickTest()
{
    var dictionary = new Dictionary<string, EntityProperty>();
    dictionary.Add("FirstName", new EntityProperty("John"));
    dictionary.Add("LastName", new EntityProperty("Doe"));

    var person = TableEntity.ConvertBack<FamousPerson>(dictionary, new OperationContext());
    Assert.AreEqual("John", person.FirstName);
}

public class FamousPerson
{
    public string FirstName { get; set; }
}
```

Given the no schema nature of table storage, it seems like this shouldn't throw an exception, or at least there should be the option to tell it to not throw an exception on missing properties. 

The issue is consistent.

Here are the exception details received.
  Message: 
    Test method Wells.DataAccess.TableStorage.UnitTests.TableStorageDataReaderTests.FindShould.QuickTest threw exception: 
    System.NullReferenceException: Object reference not set to an instance of an object.
  Stack Trace: 
    EntityPropertyConverter.SetProperty(Object root, String propertyPath, Object propertyValue, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext)
    <>c__DisplayClass4_0`1.<ConvertBack>b__0(T current, KeyValuePair`2 kvp)
    Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
    EntityPropertyConverter.ConvertBack[T](IDictionary`2 flattenedEntityProperties, EntityPropertyConverterOptions entityPropertyConverterOptions, OperationContext operationContext)
    EntityPropertyConverter.ConvertBack[T](IDictionary`2 flattenedEntityProperties, OperationContext operationContext)
    TableEntity.ConvertBack[TResult](IDictionary`2 properties, OperationContext operationContext)
    FindShould.QuickTest() line 66

**Comment by PaulCheng** [comment]
This was addressed in v1.0.7.
That said, TableEntityAdapter is not the usage pattern we want to support going forward. We'll mark the class as obsolete in v.1.0.9 and remove in v2.0.0+. That applies to the ConvertBack method as well.
It's recommended to derive from TableEntity class.

**Comment by PaulCheng** [comment]
@kyleherzog, there is no plan to fix this in 2.0.0-preview. Are you able to reference v1.0.8 instead?

**Comment by kyleherzog** [comment]
We can't drop back to 1.0.8 at this point, as we are leveraging new functionality in the 2.0.0-preview and have been for many months now.  We had noticed that it was planned for the TableEntityAdapter to be removed in future versions, but didn't see any mention of the TableEnity.ConvertBack method being removed as well.  

We do leverage the TableEntityAdapter a lot today.   The TableEntity.ConvertBack method seemed like an alternate path for us that wouldn't require too much effort.  With both of these being removed, it seems it is going to be a much more painful transition.

**Comment by PaulCheng** [comment]
@kyleherzog ConvertBack is exclusively used by the derived TableEntityAdapter class throughout the table sdk code base.
In addition, there is no more feature work planned on 2.0.0-preview. We are working toward deprecating the internal cosmos execution mode, so the next 2.0+ version will again be a major release with many changes including namespace.
Can you create a support request from Azure Portal -> CosmosDB -> Help+Support, so our CosmosDB Table API support engineer can better work with you for a path forward?

**Comment by PaulCheng** [comment]
please file a support request for further assistance or clarification.
