### ISSUE TITLE
Make CloudTable.Exists Virtual

### ISSUE THREAD

**Issue by Andrei15193** [Azure/azure-cosmos-table-dotnet#66]
* SDK version: 1.0.8
* Issue reproduce steps: Try to override Exists method
* Whether the issue is consistent or sporadic: Consistent
* Environment Summary: I'm currently developing a small library that offers an in-memory implementation of CloudTable to use in testing, all other methods regarding table operations are virtual and I can override them, but the Exists method (and the ones regarding shared access signature)
* Any other context, such as stack trace or log: Anything that is useful for having an in-memory implementation would be appreciated 😃

**Comment by PaulCheng** [comment]
CloudTable Exists method will be deprecated in the future releases.

**Comment by Andrei15193** [comment]
Will ExistsAsync still be available? What about other synchronous operations?

**Comment by PaulCheng** [comment]
@Andrei15193 You can take a look of the new SDK. it's in beta4.
https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/tables/Azure.Data.Tables

**Comment by Andrei15193** [comment]
@PaulCheng oh, I see. Lots of changes happening. Will the new [Azure.Data.Tables](https://www.nuget.org/packages/Azure.Data.Tables) package replace [Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table) NuGet package for working with Azure Table Storage?

**Comment by PaulCheng** [comment]
Yes, Azure.Data.Tables is meant to be used against both Storage Table and CosmosDB Table API endpoints.

**Comment by Andrei15193** [comment]
Cool, thanks for the info! Is it ok if I close the ticket?
