### ISSUE TITLE
UseRestExecutorForCosmosEndpoint Migrating Guideline from v1.0.8 to v.2.0.0-preview

### ISSUE THREAD

**Issue by e212156822000** [Azure/azure-cosmos-table-dotnet#84]
## Issue
I'm using Microsoft.Azure.Cosmos.Table, and hoping to migrate it from v1.0.8 to v2.0.0-preview. Below is my code snip, but I found `UseRestExecutorForCosmosEndpoint` is no longer used in v2.0.0-preview.
```
             _tableClient = storageAccount.CreateCloudTableClient(new TableClientConfiguration()
            {
                RestExecutorConfiguration = new RestExecutorConfiguration()
                {
                    HttpClientTimeout = TimeSpan.FromSeconds(10),
                    DelegatingHandler = null
                },
                UseRestExecutorForCosmosEndpoint = true
            });
```
## Asking
In v2.0.0-preview, there is no `UseRestExecutorForCosmosEndpoint` for program to specify a REST mode. What is the default mode in v2.0.0-preview? How do I specify the REST mode in v2.0.0-preview? Could you kindly provide me with some documents? Thank you.

## SDK version
v1.0.8 -> v2.0.0-preview

## Reference
v1.0.8: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tableclientconfiguration?view=azure-dotnet
v2.0.0-preview: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.table.tableclientconfiguration?view=azure-dotnet-preview

**Comment by pitscherer** [comment]
Jolin,

The package you are referencing is deprecated. Please have a look at this link:
https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/2.0.0-preview?_src=template

Peter

**Comment by e212156822000** [comment]
You're right. Thanks for the prompt information.
